1-install_nginx_web_server re wrote

diff --git a/0x0C-web_server/1-install_nginx_web_server b/0x0C-web_server/1-install_nginx_web_server
--- a/0x0C-web_server/1-install_nginx_web_server
+++ b/0x0C-web_server/1-install_nginx_web_server
@@ -1,14 +1,25 @@
 #!/usr/bin/env bash
-# Bash script that configures a new Ubuntu machine
-# it Install nginx on on server web-01
-# When querying Nginx at its root / with a GET request (requesting a page) using curl, it must return a page that contains the string Hello World!
-# can’t use systemctl for restarting nginx
 
+# Check if the number of arguments is less than 4
+if [ "$#" -lt 4 ]; then
+    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+    exit 1
+fi
 
-sudo apt-get update
-# Updated package list and install nginx
-sudo apt-get install -y nginx
-echo "Hello World!" > /var/www/html/index.html
-ufw allow 'Nginx HTTP'
-# Restart nginx (without using systemctl)
-sudo nginx -t && sudo service nginx restart
+# Assign arguments to variables
+file_path="$1"
+server_ip="$2"
+username="$3"
+ssh_key_path="$4"
+
+# Transfer the file using scp with strict host key checking disabled
+scp -o StrictHostKeyChecking=no -i "$ssh_key_path" "$file_path" "$username@$server_ip":~/
+
+# Check if the transfer was successful
+if [ "$?" -eq 0 ]; then
+    echo "File transferred successfully to $username@$server_ip:~/"
+else
+    echo "File transfer failed"
+    exit 1
+fi
+
