Check for exit code directly

diff --git a/0x0C-web_server/3-redirection b/0x0C-web_server/3-redirection
--- a/0x0C-web_server/3-redirection
+++ b/0x0C-web_server/3-redirection
@@ -11,9 +11,10 @@ echo "Hello World!" | sudo tee /var/www/html/index.html
 sudo sed -i '33i\\tlocation /redirect_me {\n\t\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n\t}\n' /etc/nginx/sites-enabled/default
 
 # Check Nginx configuration syntax
-nginx -t
-
-# If configuration syntax is correct, restart Nginx
-if [ $? -eq 0 ]; then
+if nginx -t; then
+    # Restart Nginx if configuration syntax is correct
     sudo service nginx restart
+else
+    echo "Nginx configuration syntax check failed. Exiting..."
+    exit 1
 fi
